tests: Clarify error message and fix return codes
Reported-by: Michael J. Evans
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

diff --git a/src/tests/lxc-test-ubuntu b/src/tests/lxc-test-ubuntu
--- a/src/tests/lxc-test-ubuntu
+++ b/src/tests/lxc-test-ubuntu
@@ -34,15 +34,15 @@ FAIL() {
 # Only run on a normally configured ubuntu lxc system
 if [ ! -d /sys/class/net/lxcbr0 ]; then
 	echo "lxcbr0 is not configured."
-	exit 0
+	exit 1
 fi
 if [ "$(id -u)" != "0" ]; then
-	echo "Must run as root."
-	exit 0
+	echo "ERROR: Must run as root."
+	exit 1
 fi
 if ! which host 2>&1 > /dev/null; then
 	echo "'host' program not found.  Please install bind9-host"
-	exit 0
+	exit 1
 fi
 
 for template in ubuntu ubuntu-cloud; do
