fix OpenMandriva template

diff --git a/templates/lxc-openmandriva.in b/templates/lxc-openmandriva.in
--- a/templates/lxc-openmandriva.in
+++ b/templates/lxc-openmandriva.in
@@ -9,6 +9,7 @@
 
 # Authors:
 # Alexander Khryukin <alexander@mezon.ru>
+# Vokhmin Alexey V   <avokhmin@gmail.com>
 
 # This library is free software; you can redistribute it and/or
 # modify it under the terms of the GNU Lesser General Public
@@ -25,8 +26,8 @@
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 
 #Configurations
-distro=cooker
-arch=$(uname -m)
+#distro=cooker
+hostarch=$(uname -m)
 cache_base=@LOCALSTATEDIR@/cache/lxc/openmandriva/$arch
 default_path=@LXCPATH@
 default_profile=default
@@ -115,7 +116,8 @@ create_chroot_openmandriva()
     PKG_LIST="basesystem-minimal locales locales-en initscripts urpmi cronie dhcp-client"
     # download a mini openmandriva into a cache
     echo "Downloading openmandriva minimal ..."
-    URPMI="/usr/sbin/urpmi.addmedia --urpmi-root $INSTALL_ROOT main http://abf.rosalinux.ru/downloads/$distro/repository/$arch/main/release"
+    #URPMI="/usr/sbin/urpmi.addmedia --urpmi-root $INSTALL_ROOT main http://abf.rosalinux.ru/downloads/$distro/repository/$arch/main/release"
+    URPMI="/usr/sbin/urpmi.addmedia --urpmi-root $INSTALL_ROOT main http://abf.rosalinux.ru/downloads/$release/repository/$arch/main/release"
     echo $URPMI
     URPMI_BASE="/usr/sbin/urpmi --no-suggests --no-verify-rpm --ignorearch --root $INSTALL_ROOT --urpmi-root $INSTALL_ROOT --auto $PKG_LIST"
     $URPMI
@@ -283,7 +285,7 @@ clean()
         echo -n "Purging the download cache for OpenMandriva-$release..."
         rm --preserve-root --one-file-system -rf $cache && echo "Done." || exit 1
         exit 0
-    ) 200>/var/lock/subsys/lxc-openmandriva
+    ) 200>@LOCALSTATEDIR@/lock/subsys/lxc-openmandriva
 }
 
 usage()
@@ -291,7 +293,7 @@ usage()
     cat <<EOF
 usage:
     $1 -n|--name=<container_name>
-        [-p|--path=<path>] [-c|--clean] [-R|--release=<OpenMandriva/Rosa release>]
+        [-p|--path=<path>] [-c|--clean] [-R|--release=<openmandriva2013.0/rosa2012.1/cooker/ release>]
         [-4|--ipv4=<ipv4 address>] [-6|--ipv6=<ipv6 address>]
         [-g|--gw=<gw address>] [-d|--dns=<dns address>]
         [-P|--profile=<name of the profile>] [--rootfs=<path>]
@@ -302,26 +304,39 @@ Mandatory args:
 Optional args:
   -p,--path         path to where the container rootfs will be created, defaults to @LXCPATH@. The container config will go under @LXCPATH@ in that case
   -c,--clean        clean the cache
-  -R,--release      OpenMandriva/Rosa release for the new container. if the host is OpenMandriva, then it will default to the host's release.
+  -R,--release      openmandriva2013.0/cooker/rosa2012.1 release for the new container. if the host is OpenMandriva, then it will default to the host's release.
   -4,--ipv4         specify the ipv4 address to assign to the virtualized interface, eg. 192.168.1.123/24
   -6,--ipv6         specify the ipv6 address to assign to the virtualized interface, eg. 2003:db8:1:0:214:1234:fe0b:3596/64
   -g,--gw           specify the default gw, eg. 192.168.1.1
   -G,--gw6          specify the default gw, eg. 2003:db8:1:0:214:1234:fe0b:3596
   -d,--dns          specify the DNS server, eg. 192.168.1.2
   -P,--profile      Profile name is the file name in /etc/lxc/profiles contained packages name for install to cache.
-  -A,--arch         NOT USED YET. Define what arch the container will be [i686,x86_64]
+  -A,--arch         Define what arch the container will be [i586,x86_64,armv7l,armv7hl]
   ---rootfs         rootfs path
   -h,--help         print this help
 EOF
     return 0
 }
 
-options=$(getopt -o hp:n:P:cR:4:6:g:d: -l help,rootfs:,path:,name:,profile:,clean,release:ipv4:ipv6:gw:dns: -- "$@")
+options=$(getopt -o hp:n:P:cR:4:6:g:d:A -l help,rootfs:,path:,name:,profile:,clean:,release:,ipv4:,ipv6:,gw:,dns:,arch: -- "$@")
 if [ $? -ne 0 ]; then
     usage $(basename $0)
     exit 1
 fi
 eval set -- "$options"
+
+release=${release:-"cooker"} 
+if [ -f /etc/lsb-release ]; then
+    . /etc/lsb-release
+    if [ "$DISTRIB_ID" = "OpenMandrivaLinux" ]; then
+        release=openmandriva2013.0
+    elif [ "$DISTRIB_ID" = "RosaDesktop.Fresh" ]; then
+	release=rosa2012.1
+    else
+	echo "This is not an OpenMandriva or ROSA release"
+        exit 1
+    fi
+fi
 
 while true
 do
@@ -333,6 +348,7 @@ do
         -P|--profile)   profile=$2; shift 2;;
         -c|--clean)     clean=$2; shift 2;;
         -R|--release)   release=$2; shift 2;;
+	-a|--arch)      arch=$2; shift 2;;
         -4|--ipv4)      ipv4=$2; shift 2;;
         -6|--ipv6)      ipv6=$2; shift 2;;
         -g|--gw)        gw=$2; shift 2;;
@@ -341,6 +357,8 @@ do
         *)              break ;;
     esac
 done
+
+arch=${arch:-$hostarch}
 
 if [ ! -z "$clean" -a -z "$path" ]; then
     clean || exit 1
@@ -361,15 +379,9 @@ if [ -z "$profile" ]; then
     profile=$default_profile
 fi
 
-if [ -z "$release" ]; then
-    if [ "$distro" == "cooker" ]; then
-	release="$distro"
-    elif [ "$is_openmandriva" ]; then
-	release=$(rpm --eval %product_version)
-    else
-	echo "This is not an OpenMandriva or ROSA release"
-        exit 1
-    fi
+if [ $hostarch = "i586" -a $arch = "x86_64" ]; then
+     echo "can't create x86_64 container on i586"
+     exit 1
 fi
 
 if [ -z "$ipv4" -a -z "$ipv6" ]; then
@@ -395,7 +407,7 @@ fi
 config_path=$default_path/$name
 cache=$cache_base/$release/$profile
 
-if [ -f $config_path/config ]; then
+if [ ! -f $config_path/config ]; then
     echo "A container with that name exists, chose a different name"
     exit 1
 fi
@@ -435,4 +447,3 @@ if [ ! -z $clean ]; then
     exit 0
 fi
 echo "container rootfs and config created"
-echo "network configured as $lxc_network_type in the $lxc_network_link"
