lxc-local: coding style
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

diff --git a/templates/lxc-local.in b/templates/lxc-local.in
--- a/templates/lxc-local.in
+++ b/templates/lxc-local.in
@@ -114,7 +114,7 @@ USERNS="$(in_userns)"
 if [ "${USERNS}" != "no" ]; then
   if [ "${USERNS}" = "yes" ]; then
     if [ -z "${LXC_MAPPED_UID}" ] || [ "${LXC_MAPPED_UID}" = "-1" ]; then
-      echo "ERROR: In a user namespace without a map." 1>&2
+      echo "ERROR: In a user namespace without a map" 1>&2
       exit 1
     fi
     MODE="user"
