CLEANING UP CODE nesting function calls

diff --git a/templates/lxc-pentoo.in b/templates/lxc-pentoo.in
--- a/templates/lxc-pentoo.in
+++ b/templates/lxc-pentoo.in
@@ -2,52 +2,49 @@
 #
 # LXC template for  Pentoo (Gentoo) ---Mainly as  Build container. but one could just as well have added uses..
 ## One can run the LXC as a virtual machine much as one dose with Virtualbox , yet CHROOT/BSD JAIL-ish..
-## or if not running one can use it as a ***CHROOT*** :-) also easy to goin from host system and publish to HTTP repo..
+## or if not running one can use it as a ***CHROOT*** :-) also easy to going from host system and publish to HTTP repo..
 # Tweaked  lxc-Pentoo.in  by Necrose99 (Michael R. Lawrence) mike@michaellawrenceit.com
 ### some functions not yet done...... **novice~y/rusty as hell bash code ahead you been warned...**
-## Spike Pentesting is the how bleeding edge can we push things and we bum from Pentoo.... test some of the nextgen pentest stuff 
-## but we try and give back....  however were at present still in Alpha... but we don't mind 
-# being the Lab monkeys for Pentoo . http://www.pentoo.ch/  :-) https://code.google.com/p/pentoo/
-### our CI Server code , One can use to really test your pentoo use LXC or Virtualbox etc, travis-CI etc. 
+## Spike Pentesting is the how bleeding edge can we push things and we bum from Pentoo.... test some of the nextgen pen-test stuff 
+## also make many of  pentoo's packages for Sabayon Entropy, so updates are easy , and for Less experienced Gentoo users & or those with limited time. 
+## but we try and give back to for Pentoo . http://www.pentoo.ch/  :-) https://code.google.com/p/pentoo/
+### our CI Server code , One can use to really test your Pentoo use LXC or Virtualbox etc, travis-CI etc. 
 ### https://github.com/Spike-Pentesting/App-witchcraft  
-## this will build a Gentoo or Sabayon repo in a virtual machine and not risk your Main install.
+## this will build a Gentoo or Sabayon repo in a virtual machine/Ultra glorified **CHROOT** and not risk your Main Pentoo install.
 ### (adds lxc to vagrant for use. with Witchcraft too) github.com/fgrehm/vagrant-lxc , (Vagrant/docker/chef/forman --manyways to script other addons to a VM etc. )
 ###  to always Gently pentest the network, and send alarm/page if shits really bad. And or ADD an IDS/SIEM tools/ 
+## drawn my inspiration from these too. https://github.com/adrienthebo/sabayon-chroot-builder bootstrap-sabayon.sh
 
-include lxc-gentoo.in 
-# gentoo arch/variant detection trimed. lxc-gentoo.in , perhaps I can retain varible ? enterd to build Gentoo
-# Container then save as a varible or reuse to call an eslect array neatly IF X86 Do... AMD64 etc. and or call some of the fucntions from gentoo-lxc.in
-# and not have too cluster F@@#$k of code and neet eligant ? bah so rusty i'll be lucky for ugly but works.
-set_default_arch()
-{
-printf "### set_default_arch: default arch/variant autodetect...\n"
-arch=$(uname -m)
-if [[ $arch =~ i.86 ]]; then
-arch="x86"
-variant="x86"
-elif [[ $arch == "x86_64" ]]; then
-arch="amd64"
-variant="amd64"
-#who knows, it may work...
-printf " => warn: unexpected arch:${arch} let me knows if it works :)\n"
-variant="${arch}"
-fi
-printf " => Got: arch=%s variant=%s\n" "${arch}" "${variant}"
-} 
-### need to get Arch then call symlink to pentoo bin profile 
-## IF AMD64 then;set the amd64 else set x86, else sparc,arm etc bin-symlink when/if supported... else use non-bin. & suffer the build/s
-## and in somecases force CROSSDEV build... ie ARM/Sparc VM on AMD64 host  etc... but call System-CPU specific symlinks... 
-#may need a means of probing for host servers actual CPU if calling crossdev supports ...for Real CPU then adding fake-CPU/realcpu crossdev.
-# eselect profile set pentoo:pentoo/default/linux/amd64/binary or the x86 equiv... ETC
-### get or prompt user to name container to Pentoo but use Gentoo Build funtions. based on arch/CPU.
-## Prebuild a gentoo container type. & its pretty bare bones... Generic. stage 3..
+#sed -i 's/ugly/beautiful/g' /home/bruno/old-friends/sue.txt  why not sed to make.conf of mine as a template. 
 
+###  Requires Gentoo, lxc-gentoo.in run gentoo then these few conversions ####{rootfs}
+{rootfs}="${PEN_rootfs} 
+{arch}={PEN_arch}
+{variant}{PEN_variant}
+##{rootfs} etc # never hurts to have a fail-safe. need to keep the var-s in this script after lxc-gentoo.in exits
+## from ${PEN_rootfs} CHROOT this script will *hotwire* the container to Pentoo spec. goal is once called it should be automatic.
+
+Include lxc-gentoo.in
+echo "Starting lxc-gentoo.in. to Build the Gentoo Stock Container"
+echo "Just Be sure to Name It Pentoo something.... "
+exec "lxc-gentoo.in"|| exit 1
+echo "Starting  Migration of The Generic Gentoo Container Adding "The Hot Sauce" of Pentoo"
 ##############@@@@@@@@@ Gentoo to Pentoo "Conversion" @@@@@@@@@@@@ ###############
-echo " Starting Gentoo to Pentoo "Conversion" "
-USE="bazaar cvs darcs +git gpg g-sorcery mercurial -squashfs subversion sync-plugin-portage test" Emerge layman svn git eix 
+
+chroot_pentoo
+setup_lang
+setup_system
+prepare_portage
 ## Lets build Layman so we can add Pentoo overlay to the Gentoo generic container and add "Spice" of Pentoo. 
-## as well as our build use cases squashfs one can add back in latter on 
-#just the initial Kernel depends will die (REAL HOST LINUX Kernel NO AUFS3) or suck ass building and could be useless
+install_layman
+
+unchroot_pentoo
+
+
+
+
+
+
 ### get or prompt user to name container to Pentoo but use Gentoo Build functions. based on arch.
 ## Don't know yet
 echo "Starting Layman & Pentoo Repo pull"
@@ -59,8 +56,9 @@ eselect profile set pentoo:pentoo/default/linux/amd64/binary
 # need ARCH/CPU detect of container array REAL HOST CPU detect (Crossdev) ie Sparc PPC BSD-Gentoo ARM on REAL-CPU...
 #eselect profile set pentoo:pentoo/default/linux/${arch}"/binary ---HMM seams too easy ? with my luck it never is...
 
-## for now lets set Bin profile for sat updates and less builds during Gentoo to Pentoo "conversion"... 
-## for binary type updates will be faster , and for the moment this will do user may switch latter
+
+
+
 ### with whatever i'll have to run pentoo in vm with x86 to probe for Exact.... string.. but I assume its close.
 # This syncs the gentoo and pentoo repos like "apt-get update" in debian
 emerge --sync
@@ -105,25 +103,15 @@ echo "Pentoo Updates compleate Happy Pentesting or Building packages "
 #!/bin/bash
 #!/sbin/runscript
 ### with a few add on commands add the Sabayon Linux Overlays. 
-## drawn my inspiration from these too. https://github.com/adrienthebo/sabayon-chroot-builder bootstrap-sabayon.sh
-### goals an easy to Install Sabayon Linux Builder container, which is Gentoo Completable , 
-#### yet faster to update & administrate...and in many cases easier and or a GP Sabayon box suitable for a server farm LXC Virtual hosting...
-#### testing packages without nuking prime Sabayon System..  ,Likewise building them & testing
+
 ###  Requires Gentoo, lxc-gentoo.in run gentoo then these few conversions ####{rootfs}
-{rootfs}="${SAB_rootfs}"    
+{rootfs}="${PEN_rootfs}"    
 ##{rootfs} # never hurts to have a fail-safe. need to keep the var in this script after lxc-gentoo.in exits
 Include lxc-gentoo.in
 echo "Starting lxc-gentoo.in. to Build the Gentoo Stock Container"
 echo "Just Be sure to Name It Sabayon something.... "
 exec "lxc-gentoo.in"|| exit 1
 echo "Starting Sabayon Migration of The Generic Gentoo Container and Adding the Sugar & Spice of Sabayon Linux Overlays..."
-chroot_sabayon
-setup_lang
-setup_system
-prepare_portage
-install_layman
-install_entropy
-unchroot_sabayon
 
 
 # Chroot into LXC container after Gentoo LXC Build proses. and do a few commands to convert. 
@@ -133,11 +121,11 @@ depend() {
    need bootmisc
  }
 ebegin "Mounting chroot directories"
-mount -o bind   /dev "${SAB_rootfs}/dev"
-mount -t devpts none "${SAB_rootfs}/dev/pts"
-mount -t tmpfs  none "${SAB_rootfs}/dev/shm"
-mount -t proc   none "${SAB_rootfs}/proc"
-mount -t sysfs  none "${SAB_rootfs}/sys"
+mount -o bind   /dev "${PEN_rootfs}/dev"
+mount -t devpts none "${PEN_rootfs}/dev/pts"
+mount -t tmpfs  none "${PEN_rootfs}/dev/shm"
+mount -t proc   none "${PEN_rootfs}/proc"
+mount -t sysfs  none "${PEN_rootfs}/sys"
 eend $? "An error occurred while mounting chroot directories"
 env-update
 source /etc/profile
@@ -153,7 +141,10 @@ locale-gen
 }
 setup_system() {
 ## ln -sf ../usr/share/zoneinfo/America/Los_Angeles /etc/localtime done prior in lxc-gentoo.in by user selection.
-echo "nameserver 8.8.8.8\n8.8.4.4 \n2001:4860:4860::8888\n2001:4860:4860::8844 " > /etc/resolv.conf  
+echo "nameserver 8.8.8.8
+8.8.4.4 
+2001:4860:4860::8888
+2001:4860:4860::8844 " > /etc/resolv.conf  
 #adds google public dns
 # sets python 2.7 as default
 eselect python set 1
@@ -161,64 +152,53 @@ env-update
 source /etc/profile
 }
 prepare_portage() {
-#emerge --sync
-echo "sys-apps/entropy ~amd64" >> /etc/portage/package.keywords/entropy
-echo "app-admin/equo ~amd64" >> /etc/portage/package.keywords/entropy
-echo "app-portage/layman git mercurial sync-plugin-portage darcs subversion  g-sorcery" > /etc/portage/package.use/layman
+emerge --sync
+
 env-update
 source /etc/profile
 }
 install_layman() {
-emerge -v --buildpkg  layman eix
-layman -a sabayon
+USE="bazaar cvs darcs +git gpg g-sorcery mercurial -squashfs subversion sync-plugin-portage test" Emerge -v layman svn git eix 
+## Lets build Layman so we can add Pentoo overlay to the Gentoo generic container and add "Spice" of Pentoo. 
+## as well as our build use cases squashfs one can add back in latter on 
+#just the initial Kernel depends will often die (REAL HOST LINUX Kernel NO AUFS3) or suck ass building and could be useless
+layman -a pentoo
 layman -S
 echo "source /var/lib/layman/make.conf" >> /etc/portage/make.conf
 env-update
 source /etc/profile
 }
-install_entropy() {
-emerge -vt app-admin/equo sys-apps/entropy --autounmask-write
-etc-update --automode -5
-emerge -vt app-admin/equo sys-apps/entropy
+set_pentoo_binprofile() {
+ ## for now lets set Bin profile for sat updates and less builds during Gentoo to Pentoo "conversion"... 
+## for binary type updates will be faster , and for the moment this will do user may switch latter
+## wildcard needed for host container type variable cloned from lxc-gentoo build. may need a filter for {PEN_variant} regular or hardened.
+## wildcard  for cpu {PEN_arch} may need filter for valid pentoo suppoted types. 
+# special thanks to ZERO CHAOS
+eselect profile set pentoo:pentoo/$"{PEN_variant}"/linux/$"{PEN_arch}"/binary
+eend $? "Error that cant be good CPU/or Invalid profile /Not suppoted by Gentoo container type"
 }
 
 
 
-unchroot_sabayon() {
+unchroot_Pentoo() {
 ebegin "Unmounting chroot directories"
-umount "${SAB_rootfs}/dev/pts"
-umount "${SAB_rootfs}/dev/shm"
-umount "${SAB_rootfs}/dev"
-umount "${SAB_rootfs}/proc"
-umount "${SAB_rootfs}/sys"
-eend $? "An error occurred while unmounting chroot directories"
-}
-sabayon_entropy_update() {
-ebegin "Entropy updates and Gentoo Source package manager migration"
-equo update
+umount "${PEN_rootfs}/dev/pts"
+umount "${PEN_rootfs}/dev/shm"
+umount "${PEN_rootfs}/dev"
+umount "${PEN_rootfs}/proc"
+umount "${PEN_rootfs}/sys"
 eend $? "An error occurred while unmounting chroot directories"
 }
 
-### Add Sabayon src repos incase we need to build., also adds package masks etc to keep bad stuff from building that don't agree with Sabayon. 
- equo update && equo repo mirrorsort sabayonlinux.org
-## update binaries package lists and repos Sort repos else you'll have GARR.. 
-## (university) in IT,  sort to fastest mirrors possible so updates are fast as possible. 
-equo rescue spmsync 
-sleep=600   # wait takes about 10-30 mins on a rescued gentoo/sab box however new box shouldn't take long. 
-### not always necessary but since migrating... sync world to entropy DB. ###
-equo install entropy equo
-## update entropy core  and equo entropy txt client 
-equo upgrade
-wait till exit ??? 
-equo deptest && equo libtest  ### tests dependancies and libs installs if required 
-wait till exit ??? 
-equo conf update   ### ???? some means of saying -5 to all (YES merge) 
-
-ECHO " Congratulations Sabayon Linux is now Installed, however only X64 is officially supported" 
+ 
+x11_Pentoo() {
+# Add some goodies later like VNC or something ? to allow use of X11 when runing in lxc and or just apps via chroot for now K,i,s,s.
 export DISPLAY=":0.0"
-pentoo_logo_end() {
-echo $"
+}
 
+pentoo_logo_end() {
+ECHO " Congratulations Sabayon Linux is now Installed,Into LXC" 
+echo $"
 8?888O888O+88888ZO$OZ8OOO888O888888$O888O8888888O8ZZOO888OZOOOOZZOOOOOOZZIZZZZZ7Z$7$$$I77I77777IIIIII?I???=:+=+=+OOOO88$O88O8ZZO8O888OO88O8O8OOZ+8888O$O8888OO$OI88OOO88888OOOO+OOO$
 87888=8888$88888?8ZO888$?888Z888888$O888ZO88ZZ8888OO8O8O8$7OOOO==OOOOOO$$7ZZZ$Z$ZZI7$$7$7777+7777IIII~?I??+=+=++++?ZOOO$=OOO8O7ZOOOOO$OOOOOOOOOO$OOOOO$OOOOOOOOO=OOOO8888O8$OOOIOOO?
 8O888O8888IO8888Z8$OO8OOO888$888888$O888OO88:=88OOOOOOOOOOOOOOOZZOOOOOOZZZOZZZ$IZZ?I$$?7II77I777IIIII?II???++=+=++==IOOOOOOOOO7ZOOOOOOOOOOOOOOOZOOOOOO$OOOOOOOOO$OOOOO88888$OOOZOOO?
@@ -257,11 +237,7 @@ OO888888888888888888888O$7O888888888888888888O7+7$=7O88888888888888888OOOOOO8OOZ
 OO88888888888888888888OI~=O888888888888888888O??ZZ=?Z88888888888888888OZZZZO8OOZ$$77$$ZZO88OZZZO88888OOOOOO8OOO8888888888888OOOOOOZZZZZZNMMMMMNOI7$Z7ONOMZZZZZZZZZZZZZZZZZZZZZZZZZZZ
 OO88888888888888888888O$I+O888888888888888888O+?ZZ=?Z88888888888888888Z?==+$8OOZ$$$7$$ZOO8OZ???Z88888OOOOOO8OOO8888888888888OOOOO8ZZZZZZZZZZZZZZDMMMMMNO8ZZZZZZZZZZZZZZZZZZZZZZZZZZZ
 OO8888O8888888888888888O7+Z888888888888888888O??ZZ=?Z888888O888888888OI=77=IOOOZ$$7$$$ZOO8O$?$I7OO888OOOOOO8OOO8888888888888OOZOO8888888888888O888888OOOOOZZZZ$ZZOO8OOOO8OOOOOOOOOZ$
-OO88888888888888888888887+ZO8888888888888OO8OOI+$$=IZO88888O88OO88888O+?OO?+OOOZZ$$$$ZZOO8O7IZ7IO8888OOZOZOOOOO8O88888888888OZ$ZOO88888O8888888888888ZOOOZZZOZZZOOOOOOOOOOOOOOOOOOO$
-                                                                                                                                                                     GlassGiant.com
-
-"
+OO88888888888888888888887+ZO8888888888888OO8OOI+$$=IZO88888O88OO88888O+?OO?+OOOZZ$$$$ZZOO8O7IZ7IO8888OOZOZOOOOO8O88888888888OZ$ZOO88888O8888888888888ZOOOZZZOZZZOOOOOOOOOOOOOOOOOOO$"
 Echo "Welcome to your Pentoo Linux container"
-
 }
-#sed -i 's/ugly/beautiful/g' /home/bruno/old-friends/sue.txt  why not sed to make.conf of mine as a template. 
+
