lxc-fedora.in
* if not running on fedora host amd -R is not set, use fedora 14 as default
* trap SIGHUP SIGINT SIGTERM, and cleanup before exiting

Signed-off-by: Daniel Lezcano <dlezcano@fr.ibm.com>

diff --git a/templates/lxc-fedora.in b/templates/lxc-fedora.in
--- a/templates/lxc-fedora.in
+++ b/templates/lxc-fedora.in
@@ -316,8 +316,7 @@ if [ -z "$release" ]; then
     if [ "$is_fedora" ]; then
         release=$(cat /etc/fedora-release |awk '/^Fedora/ {print $3}')
     else
-        echo "This is not a fedora host and release missing, use -R|--release to specify release"
-        exit 1
+        echo "This is not a fedora host and release missing, defaulting to 14. use -R|--release to specify release"
     fi
 fi
 
@@ -326,12 +325,32 @@ if [ "$(id -u)" != "0" ]; then
     exit 1
 fi
 
+
 rootfs_path=$path/$name/rootfs
 config_path=$default_path/$name
 cache=$cache_base/$release
 
 if [ -f $config_path/config ]; then
     echo "A container with that name exists, chose a different name"
+    exit 1
+fi
+
+revert()
+{
+    echo "Interrupted, so cleaning up"
+    lxc-destroy -n $name
+    # maybe was interrupted before copy config
+    rm -rf $path/$name
+    rm -rf $default_path/$name
+    echo "exiting..."
+    exit 1
+}
+
+trap revert SIGHUP SIGINT SIGTERM
+
+copy_configuration
+if [ $? -ne 0 ]; then
+    echo "failed write configuration file"
     exit 1
 fi
 
@@ -347,11 +366,6 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-copy_configuration
-if [ $? -ne 0 ]; then
-    echo "failed write configuration file"
-    exit 1
-fi
 
 if [ ! -z $clean ]; then
     clean || exit 1
